services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: "test-postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/postgres-data:/var/lib/postgresql/data